# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy two container apps to Azure Web App - api + dashboard

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  packages: 'write'

jobs:
   test:

    runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v3
     - name: Set up Python 3.10
      uses: actions/setup-python@v3
       with:
         python-version: "3.10"
     - uses: actions/cache@v3
       id: cache
       with:
         path: ~/.cache/pip
         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.*') }}
         restore-keys: | 
           ${{ runner.os }}-pip-
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r tests/requirements.txt        
     - name: Run pytest
       run: | 
         pytest

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: appregistryhw0.azurecr.io/
          username: ${{ secrets.AZURE_CONTAINER_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_PASSWORD }}

      - name: Build and push dashboard to registry
        uses: docker/build-push-action@v2
        with:
          context: ./dashboard
          push: true
          tags: appregistryhw0.azurecr.io/dashboard:${{ github.sha }}
          file: ./dashboard/Dockerfile

      - name: Build and push api to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: appregistryhw0.azurecr.io/api:${{ github.sha }}
          file: ./api/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy Dashboard to Azure Web App
        id: deploy-to-webapp-dashboard
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dashboard'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'appregistryhw0.azurecr.io/dashboard:${{ github.sha }}'

      - name: Deploy API to Azure Web App
        id: deploy-to-webapp-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'main'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'appregistryhw0.azurecr.io/api:${{ github.sha }}'