name: Continuous Integration and Continuous Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:  
  CI: # Continous Integration
    runs-on: 'ubuntu-latest'
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name : Set-up Python V3.9.13
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.13
    - name : Install Dependancies
      run: |
        pip install -r requirements.txt
        pip install pytest
    - name: Test with pytest
      run: |
        pytest #python -m pytest

  CD: # Continuous Deployment
    needs: [CI]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v3
    - #name: Deploy on Render.com
      run: wget http://127.0.0.1:8000