name: auto test while pushing main.py 

on:
  push:
    branches:
      - main
    
jobs:  
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name : Set-up Python V3.9.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.13
    - name : Install Dependancies
      run: |
        pip install -r requirements.txt
        pip install pytest
    - name: Test with pytest
      run: |
        pytest #python -m pytest

    #- name: Deploy

     # run: wget https://api.render.com/deploy/srv-cojcudsf7o1s73akm6vg?key=KM1Mq7yvjkk