name: auto test while pushing main.py 

on:
  push:
    branches:
      - main
    
jobs:  
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name : Set-up Python V3.9.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.9.13

    - name : Install Dependancies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Test with pytest
      run: |
        pytest #python -m pytest

    - name: Deploy

      run: wget https://api.render.com/deploy/srv-cok9ikud3nmc7396g86g?key=850I3AKwxaI